"""style_training

Revision ID: 46f76541c132
Revises: f8937ae4e76e
Create Date: 2026-07-15 23:27:15.910114
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '46f76541c132'
down_revision: Union[str, Sequence[str], None] = 'f8937ae4e76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_training_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('source_char_count', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_training_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_training_proposals_status'), ['status'], unique=False)

    op.create_table('style_profile_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('source_proposal_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['style_training_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_style_profile_version')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_profile_versions')
    with op.batch_alter_table('style_training_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_training_proposals_status'))

    op.drop_table('style_training_proposals')
    # ### end Alembic commands ###
