"""publication_analytics_and_profile_versions

Revision ID: 668a4577ae2e
Revises: 46f76541c132
Create Date: 2026-07-15 23:50:29.651371
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '668a4577ae2e'
down_revision: Union[str, Sequence[str], None] = '46f76541c132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('note_url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_title', sa.String(length=240), nullable=False),
    sa.Column('final_version_id', sa.String(length=36), nullable=True),
    sa.Column('final_tags', sa.JSON(), nullable=False),
    sa.Column('final_cover_path', sa.String(length=1000), nullable=True),
    sa.Column('recommended_publish_time', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_version_id'], ['content_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', name='uq_publication_content')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_content_id'), ['content_id'], unique=False)

    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('calculated_rates', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'day_offset', name='uq_publication_day_snapshot')
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_publication_id'), ['publication_id'], unique=False)

    with op.batch_alter_table('style_profile_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_type', sa.String(length=30), server_default='training', nullable=False))
        batch_op.add_column(sa.Column('source_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_profile_versions', schema=None) as batch_op:
        batch_op.drop_column('source_version')
        batch_op.drop_column('change_type')

    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_publication_id'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_content_id'))

    op.drop_table('publications')
    # ### end Alembic commands ###
