"""initial_schema

Revision ID: f8937ae4e76e
Revises:
Create Date: 2026-07-15 22:35:35.177096
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f8937ae4e76e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=240), nullable=False),
    sa.Column('emotion', sa.String(length=120), nullable=False),
    sa.Column('extra_requirements', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('selected_plan_id', sa.String(length=100), nullable=True),
    sa.Column('selected_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_status'), ['status'], unique=False)

    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'version', name='uq_content_version')
    )
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_versions_content_id'), ['content_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_content_id'), ['content_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('step_id', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_content_id'), ['content_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('output_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('tool_permissions', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_workflow_step_idempotency')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_steps_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_steps_content_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_content_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_content_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_versions_content_id'))

    op.drop_table('content_versions')
    op.drop_table('api_usage')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_status'))

    op.drop_table('contents')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
